"""Compatibility re-exports for hosted-tool specs.

New code should import specs from :mod:`blackbox.tools.hosted.specs`.
Runtime-side hosted-tool call/result contracts live in
:mod:`blackbox.tools.hosted.calls`.
"""

from blackbox.tools.hosted.specs import (
    ApplyPatch,
    CodeInterpreter,
    ComputerUse,
    ContainerSpec,
    FileSearch,
    HostedExecutionMode,
    HostedToolHandler,
    HostedToolHandlers,
    HostedToolRaw,
    HostedToolSpec,
    ImageGeneration,
    MCPApprovalPolicy,
    Memory,
    RemoteMCP,
    Shell,
    TextEditor,
    ToolNamespace,
    ToolSearch,
    URLContext,
    WebFetch,
    WebSearch,
    anthropic_beta_values,
    anthropic_deferred_tools,
    anthropic_mcp_servers,
    hosted_tool_kind,
    openai_include_values,
    openai_namespace_tools,
    to_anthropic_tool,
    to_gemini_tool,
    to_openai_tool,
    to_raw_hosted_tool,
)

__all__ = [
    "ApplyPatch",
    "CodeInterpreter",
    "ComputerUse",
    "ContainerSpec",
    "FileSearch",
    "HostedExecutionMode",
    "HostedToolHandler",
    "HostedToolHandlers",
    "HostedToolRaw",
    "HostedToolSpec",
    "ImageGeneration",
    "MCPApprovalPolicy",
    "Memory",
    "RemoteMCP",
    "Shell",
    "TextEditor",
    "ToolNamespace",
    "ToolSearch",
    "URLContext",
    "WebFetch",
    "WebSearch",
    "anthropic_beta_values",
    "anthropic_deferred_tools",
    "anthropic_mcp_servers",
    "hosted_tool_kind",
    "openai_include_values",
    "openai_namespace_tools",
    "to_anthropic_tool",
    "to_gemini_tool",
    "to_openai_tool",
    "to_raw_hosted_tool",
]
