from importlib import import_module
from typing import Any

from agent_runtime.compat.chat import ChatMessage
from agent_runtime.compat.providers import (
    ModelRoute,
    create_runtime_with_default_providers,
    provider_ref_for_model,
    register_default_model_providers,
    resolve_model_route,
)
from agent_runtime.core.accounting import ModelCatalog, ModelPricing, ModelUsage
from agent_runtime.core.approvals import ApprovalDecision, ApprovalRequest
from agent_runtime.core.artifacts import Artifact, ArtifactRef
from agent_runtime.core.cache import (
    InMemoryProviderCacheStore,
    ProviderCacheRecord,
    ProviderCacheStore,
    ProviderCacheUsage,
    SQLiteProviderCacheStore,
)
from agent_runtime.core.capabilities import (
    AgentCapabilities,
    CapabilityConstraint,
    CapabilityDetail,
    HostedToolSupport,
    ModelCapabilities,
    ModelCapabilityProfile,
)
from agent_runtime.core.content import (
    AudioPart,
    ContentItem,
    ContentPart,
    FilePart,
    ImagePart,
    ProviderNativePart,
    TextPart,
    ToolResultPart,
    VideoFramePart,
)
from agent_runtime.core.errors import OutputValidationError
from agent_runtime.core.events import AgentEvent, EventTypes
from agent_runtime.core.items import ItemTypes, RunItem
from agent_runtime.core.media import MediaRef
from agent_runtime.core.realtime import ToolMode, TransportKind
from agent_runtime.core.results import (
    AgentResult,
    AgentSessionResult,
    AgentSessionResultStatus,
    ToolPayload,
)
from agent_runtime.core.sessions import AgentRef, AgentSession, SessionRef
from agent_runtime.core.state import ProviderState, RunState
from agent_runtime.hosted_tools import (
    ApplyPatch,
    CodeInterpreter,
    ComputerUse,
    ContainerSpec,
    FileSearch,
    HostedToolHandlers,
    HostedToolRaw,
    ImageGeneration,
    Memory,
    RemoteMCP,
    Shell,
    TextEditor,
    ToolNamespace,
    ToolSearch,
    URLContext,
    WebFetch,
    WebSearch,
)
from agent_runtime.mcp import MCPServerSpec, MCPToolset
from agent_runtime.output.schema import OutputSchema
from agent_runtime.planning.prompts import (
    CacheSection,
    FragmentRequirements,
    FragmentSelector,
    PromptBundle,
    PromptComposer,
    PromptFragment,
    PromptFragmentRegistry,
    PromptParityIssue,
    PromptSection,
    PromptSpec,
    SelectedPromptFragment,
    SkippedPromptFragment,
    assert_prompt_tool_parity,
)
from agent_runtime.planning.run_plan import (
    DataSourceRef,
    DynamicToolLoadingSpec,
    ResolvedHostedTool,
    ResolvedMCPToolset,
    ResolvedRunSpec,
    ResolvedTool,
)
from agent_runtime.providers.base import (
    AgentProvider,
    AgentSpec,
    CompactionControl,
    ModelCacheControl,
    ModelProvider,
    ModelRequestControls,
    TaskSpec,
    ToolSearchControl,
    TurnRequest,
    TurnResult,
)
from agent_runtime.providers.registry import ProviderRef, ProviderRegistry
from agent_runtime.realtime import (
    AudioConfig,
    FakeRealtimeProvider,
    ManagedRealtimeSession,
    RealtimeCapabilities,
    RealtimeCapabilityProfile,
    RealtimeClientCommand,
    RealtimeConnectRequest,
    RealtimeProvider,
    RealtimeRuntime,
    RealtimeSessionConfig,
    RealtimeSessionRef,
    TurnDetectionConfig,
    register_default_realtime_providers,
)
from agent_runtime.runtime import (
    AgentRuntime,
    AgentRuntimeFacade,
    ChatRuntimeFacade,
    ModelRuntime,
    PromptRuntimeFacade,
    ProviderCacheRuntime,
    WorkspaceRuntimeFacade,
)
from agent_runtime.tools.session import ToolSession
from agent_runtime.workspace_agents import (
    ApprovalRequirement,
    ConnectorSpec,
    InMemoryWorkspaceAgentRegistry,
    MemorySpec,
    PublicationSpec,
    ScheduledRunRef,
    ScheduleSpec,
    ScheduleTrigger,
    SkillBundleRef,
    ToolPermission,
    WorkspaceAgentMetadata,
    WorkspaceAgentRegistry,
    WorkspaceAgentSpec,
    WorkspaceAgentVersion,
    dataclass_from_dict,
    dataclass_to_dict,
    prepare_agent_spec,
    run_workspace_agent,
    workspace_agent_from_dict,
    workspace_agent_to_dict,
)

__all__ = [
    "AgentCapabilities",
    "AgentEvent",
    "AgentProvider",
    "AgentRef",
    "AgentResult",
    "AgentRuntime",
    "AgentRuntimeFacade",
    "AgentSession",
    "AgentSessionResult",
    "AgentSessionResultStatus",
    "AgentSpec",
    "ApplyPatch",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalRequirement",
    "Artifact",
    "ArtifactRef",
    "AudioConfig",
    "AudioPart",
    "CacheSection",
    "CapabilityConstraint",
    "CapabilityDetail",
    "ChatMessage",
    "ChatRuntimeFacade",
    "CodeInterpreter",
    "CompactionControl",
    "ComputerUse",
    "ConnectorSpec",
    "ContainerSpec",
    "ContentItem",
    "ContentPart",
    "DataSourceRef",
    "DynamicToolLoadingSpec",
    "EventTypes",
    "FakeRealtimeProvider",
    "FilePart",
    "FileSearch",
    "FragmentRequirements",
    "FragmentSelector",
    "GoogleBigQueryMCPAuth",
    "HostedToolHandlers",
    "HostedToolRaw",
    "HostedToolSupport",
    "ImageGeneration",
    "ImagePart",
    "InMemoryProviderCacheStore",
    "InMemoryWorkspaceAgentRegistry",
    "ItemTypes",
    "MCPServerSpec",
    "MCPToolset",
    "ManagedRealtimeSession",
    "MediaRef",
    "Memory",
    "MemorySpec",
    "ModelCacheControl",
    "ModelCapabilities",
    "ModelCapabilityProfile",
    "ModelCatalog",
    "ModelPricing",
    "ModelProvider",
    "ModelRequestControls",
    "ModelRoute",
    "ModelRuntime",
    "ModelUsage",
    "OutputSchema",
    "OutputValidationError",
    "PromptBundle",
    "PromptComposer",
    "PromptFragment",
    "PromptFragmentRegistry",
    "PromptParityIssue",
    "PromptRuntimeFacade",
    "PromptSection",
    "PromptSpec",
    "ProviderCacheRecord",
    "ProviderCacheRuntime",
    "ProviderCacheStore",
    "ProviderCacheUsage",
    "ProviderNativePart",
    "ProviderRef",
    "ProviderRegistry",
    "ProviderState",
    "PublicationSpec",
    "RealtimeCapabilities",
    "RealtimeCapabilityProfile",
    "RealtimeClientCommand",
    "RealtimeConnectRequest",
    "RealtimeProvider",
    "RealtimeRuntime",
    "RealtimeSessionConfig",
    "RealtimeSessionRef",
    "RemoteMCP",
    "ResolvedHostedTool",
    "ResolvedMCPToolset",
    "ResolvedRunSpec",
    "ResolvedTool",
    "RunItem",
    "RunState",
    "SQLiteProviderCacheStore",
    "ScheduleSpec",
    "ScheduleTrigger",
    "ScheduledRunRef",
    "SelectedPromptFragment",
    "SessionRef",
    "Shell",
    "SkillBundleRef",
    "SkippedPromptFragment",
    "TaskSpec",
    "TextEditor",
    "TextPart",
    "ToolMode",
    "ToolNamespace",
    "ToolPayload",
    "ToolPermission",
    "ToolResultPart",
    "ToolSearch",
    "ToolSearchControl",
    "ToolSession",
    "TransportKind",
    "TurnDetectionConfig",
    "TurnRequest",
    "TurnResult",
    "URLContext",
    "VideoFramePart",
    "WebFetch",
    "WebSearch",
    "WorkspaceAgentMetadata",
    "WorkspaceAgentRegistry",
    "WorkspaceAgentSpec",
    "WorkspaceAgentVersion",
    "WorkspaceRuntimeFacade",
    "assert_prompt_tool_parity",
    "create_runtime_with_default_providers",
    "dataclass_from_dict",
    "dataclass_to_dict",
    "google_application_default_bigquery_auth",
    "google_bigquery_mcp_toolset",
    "google_maps_mcp_toolset",
    "prepare_agent_spec",
    "provider_ref_for_model",
    "register_default_model_providers",
    "register_default_realtime_providers",
    "resolve_model_route",
    "run_workspace_agent",
    "workspace_agent_from_dict",
    "workspace_agent_to_dict",
]

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "GoogleBigQueryMCPAuth": (
        "agent_runtime.integrations",
        "GoogleBigQueryMCPAuth",
    ),
    "google_application_default_bigquery_auth": (
        "agent_runtime.integrations",
        "google_application_default_bigquery_auth",
    ),
    "google_bigquery_mcp_toolset": (
        "agent_runtime.integrations",
        "google_bigquery_mcp_toolset",
    ),
    "google_maps_mcp_toolset": (
        "agent_runtime.integrations",
        "google_maps_mcp_toolset",
    ),
}


def __getattr__(name: str) -> Any:
    try:
        module_name, attr_name = _LAZY_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value
